baseurl             = "https://wazeerzulfikar.github.io/" # Must end with /
languageCode        = "en-us"
title               = "Wazeer Zulfikar"
theme               = "introduction"
enforce_ssl         = "your-url.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# disqusshortname   = "wzulfikar" # Enable Disqus for comments
# googleAnalytics   = "xxx"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Wazeer Zulfikar" # Full name shows on blog post pages
firstname     = "Wazeer" # First name shows in introduction on main page
tagline       = "Code • Gym • Travel" # Appears after the introduction
introheight   = "large" # Input either 'medium' or 'large' or 'fullheight'
theme         = "light" # Choose 'light' or 'dark'
avatar        = "img/avatar.png" # Path to image in static folder eg. img/avatar.png
email         = "wazeer.zulfikar@gmail.com" # Shows in contact section, or leave blank to omit
localtime     = true # Show your current local time in contact section
timezone      = "Asia/Kolkata" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "Website Description"
faviconfile   = "img/fav.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "" # Text to show in footer (overrides default text)
fadein        = true # Turn on/off the fade-in effect

showblog        = false # Show Blog section on home page
showblogs		= true
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = false # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

blogs1 = "GSoC '17 Blog"
blogs1link = "/gsoc-blog/"

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "http://github.com/wazeerzulfikar/rtensorflow"
project1img     = "img/gsoc.png"
project1title   = "GSoC '17 Project"

project2link    = "https://github.com/wazeerzulfikar/traffic-signs-recognition"
project2img     = "img/traffic.jpg"
project2title   = "Traffic Sign Recognition"

project3link    = "#"
project3img     = "img/coming-soon.png"
project3title   = ""


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
url = "https://github.com/wazeerzulfikar"
icon = "github"

[[params.social]]
url = "https://www.facebook.com/wazeer.zulfikar"
icon = "facebook"

[[params.social]]
url = "https://in.linkedin.com/in/wazeer-zulfikar-29794b130"
icon = "linkedin"
